<a href="https://colab.research.google.com/github/jixuanlu/assignment/blob/master/1.2Linear%20Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 1. Linear Algebra

In [ ]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# creat specific array
a = np.zeros(10)
b = np.ones(10)
c = np.zeros(10) + 5
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# use random numbers to populate an array
a = np.random.rand(10)
print(a)

[0.03972459 0.75215587 0.47380604 0.46069809 0.11795019 0.27968509
 0.45134362 0.38147243 0.34381003 0.50316647]


In [ ]:

# print index of the array
a = np.arange(10)
print(a)
print(a[-1])
print(a[1:3])
print(a[1:5:2])

[0 1 2 3 4 5 6 7 8 9]
9
[1 2]
[1 3]


  1.2 Elements of Linear Algebra

Basic operation of matrix

In [ ]:
a = np.zeros((3, 5))
# note the extra bracket you need for calling np.zeros
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

len = 3
shape = (3, 5)


In [ ]:
# pick two output valuables from a method
a = np.zeros((3,5))
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

nx = 3
ny = 5


In [ ]:
# ways to generate a constant array

a = np.zeros((3,5)) + 7
print(a, '\n')

b = np.ones((3,5)) * 7
print(b, '\n')

c = np.full((3,5), 7)
print(c)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
# identity matrix function eye()
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# index
a = np.array(([1,2], [3,4], [5,6]))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
# mix integer and slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[1, :]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [ ]:
# use two list as index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[[0,1,2],[2,1,2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 3  6 11]


In [ ]:
# update values
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[1,:] += 10
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [ 0.  1.  2.]]


In [ ]:
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[:,2] = 5.
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[0. 1. 5.]
 [0. 1. 5.]
 [0. 1. 5.]]


In [ ]:
# type of data in the array
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype)

[[1 1]
 [1 1]]
int64


In [ ]:
a=np.array(([1.,1],[1,1]))
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64


In [ ]:

a=np.array(([1.,1],[1,1]))>2
print(a)
print(a.dtype)

[[False False]
 [False False]]
bool


In [ ]:
a=np.array((['1','1'],['1','1']))
print(a)
print(a.dtype)

[['1' '1']
 ['1' '1']]
<U1


In [ ]:
a=np.array((['1','1'],['1','1']),dtype=float)
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64


In [ ]:

a = np.zeros((3, 5))
# note the extra bracket you need for calling np.zeros
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

In [ ]:

# pick two output valuables from a method
a = np.zeros((3,5))
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

In [ ]:
# ways to generate a constant array

a = np.zeros((3,5)) + 7
print(a, '\n')

b = np.ones((3,5)) * 7
print(b, '\n')

c = np.full((3,5), 7)
print(c)

In [ ]:

# identity matrix function eye()
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# index
a = np.array(([1,2], [3,4], [5,6]))
print(a)

In [ ]:
# slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

In [ ]:
# mix integer and slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[1, :]
print(b)

In [ ]:
# use two list as index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[[0,1,2],[2,1,2]])

In [ ]:
# update values
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[1,:] += 10
print('after\n',a)

In [ ]:
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[:,2] = 5.
print('after\n',a)

In [ ]:
# type of data in the array
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype)

In [ ]:
a=np.array(([1.,1],[1,1]))
print(a)
print(a.dtype)

In [ ]:

a=np.array(([1.,1],[1,1]))>2
print(a)
print(a.dtype)

In [ ]:
a=np.array((['1','1'],['1','1']))
print(a)
print(a.dtype)

In [ ]:
a=np.array((['1','1'],['1','1']),dtype=float)
print(a)
print(a.dtype)

In [ ]:

# most numpy functions can be applied directly to an array
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print(a)
print(a >= 1)
print(np.sqrt(a))

In [ ]:
# inversion
A = np.matrix([[1,0,0],
               [0,1,0],
               [0,0,1]])

B = np.matrix([[3,1],
               [1,3]])

print(A, '\n')
print(np.trace(A), '\n')
print(np.invert(A), '\n')

print(B, '\n')
print(np.trace(B), '\n')
print(np.invert(B))

In [ ]:
# numpy.linalg.eig(a)     Calculate the eigenvalues and eigenvectors of the square matrix.
# numpy.linalg.eigvals(a) Calculate the eigenvalues of the square matrix.

x = np.diag([1,2,3])
print(np.linalg.eigvals(x))

a, b = np.linalg.eig(x)
print('eigenvalue：', a, '\n')
print('eigenvector：\n', b, '\n')


# verify that the eigenvalues and eigenvectors are correct
for i in range(3):       
    if np.allclose(a[i] * b[:, i], np.dot(x, b[:, i])):
        print('Correct')
    else:
        print('Wrong')

In [ ]:
# two arrays
a = np.zeros((3,3))
b = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
    b[i,:] = i
print('a=\n', a)
print('b=\n', b)

print('a+b=\n', a + b)
print('a*b=\n', a * b)
print('a/b=\n', a / b) # notice the first row of the result

In [ ]:
# broadcasting
# add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([2, 0, 1])
y = x + v
z = x * v
print(y, '\n')
print(z)

In [ ]:
# dot product
x = np.array([1,2,3,4,5])
y = np.array([2,3,4,5,6])
z = np.dot(x,y)  #  The dot product of two vectors
print(z)

x = np.array([[1,2,3],[3,4,5],[6,7,8]])
y = np.array([[5,4,2],[1,7,9],[0,4,5]])
z= np.dot(x,y)   #  matrix multiplication
print(z)

In [ ]:
a = np.array([1,2])
b = np.array([3,4]) 
c = np.array([[3],[4]])

print(b*a) 
print(a*c)  #  A matrix multiplies its elements, so it satisfies the commutative law
print(c*a)

print(np.dot(a,b))    #  matrix multiplication
print(np.dot(a,c))
#print(np.dot(c,a)) There will be an error

In [ ]:
# cross product
a = [1,2,3]
b = [2,3,4]

c = np.cross(a,b)
print(c)

In [ ]:
# matrix multiplication
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

c = np.matmul(a,b)
print(c)

In [ ]:
# transpose
a = np.array(([1,2], [3,4],[ 5,6]))
print('a=\n',a)
print('a.T=\n',a.T)
print('a.transpose()=\n',a.transpose())

In [ ]:
# reshape
a = np.array(([1,2], [3,4], [5,6]))
print('a\n', a)

b = a.reshape((2,3))
print('b\n', b)

c = a.flatten()
print('c\n', c)

# C order, row order
d = a.flatten(order = 'C')
print('d\n', d)

# Fortran order, column order
e = a.flatten(order = 'F')
print('e\n', e)

In [ ]:
# stacking
a=np.full((3,2),1.)
b=np.full((3,2),2.)
c=np.full((3,2),3.)

print('a=',a)
print('b=',b)
print('c=',c)

print('hstack=',np.hstack((a,b,c)))
print('vstack=',np.vstack((a,b,c)))

In [ ]:

# difference of python sum and numpy.sum

data = np.arange(1000)

%timeit sum(data)
%timeit np.sum(data)

In [ ]:
data = []
for i in range(1000):
    data.append(i)

%timeit sum(data)
%timeit np.sum(data)

In [ ]:
a = np.array([[8, -6, 2], [-4, 11, -7], [4, -7, 6]])
b = np.array([[28], [-40], [33]])
x = np.linalg.solve(a, b)
print(a)
print(x)

In [ ]:
m = np.array([[1, -2, 1],[0, 2, -8],[-4, 5, 9]])
v = np.array([0, 8, -9])
r = np.linalg.solve(m, v)
print('result：')
name = ['X1', 'X2', 'X3']
for i in range(len(name)):
    print(name[i] + '=' + str(r[i]))

In [ ]:
mat = np.vstack([[1,1,1],[1,-1,2],[2,0,3]])
sol = np.vstack([3,2,1])
try:
    npl.solve(mat,sol)
except:
    print(np.hstack([mat,sol]))
    print('Not solveable. Adding rows 1 and 2 contradicts row 3.')

In [ ]:
# (whether all eigenvalues are positive)
A = np.arange(16).reshape(4,4)
print(A)

A = A + A.T  # Convert square matrices to symmetric matrices
print(A)

B = np.linalg.eigvals(A)
print(B)

if np.all(B>0):
    print('Yes')
else:
    print('No')


In [ ]:
#coding:utf8

def gram_schmidt(A):
    """Gram-schmidt Orthogonalization"""
    Q=np.zeros_like(A)
    cnt = 0
    for a in A.T:
        u = np.copy(a)
        for i in range(0, cnt):
            u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i]) 
        e = u / np.linalg.norm(u)  # normalization 
        Q[:, cnt] = e
        cnt += 1
    R = np.dot(Q.T, A)
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = gram_schmidt(A)
print(Q)
print(R)
print(np.dot(Q, R))

In [ ]:
def givens_rotation(A):
    """"Givens Rotations"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    (rows, cols) = np.tril_indices(r, -1, c)
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:  
            r_ = np.hypot(R[col, col], R[row, col])  # d
            c = R[col, col]/r_
            s = -R[row, col]/r_
            G = np.identity(r)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)   # R=G(n-1,n)*...*G(2n)*...*G(23,1n)*...*G(12)*A
            Q = np.dot(Q, G.T)  # Q=G(n-1,n).T*...*G(2n).T*...*G(23,1n).T*...*G(12).T
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = givens_rotation(A)
print(Q)
print(R)
print (np.dot(Q, R))

In [ ]:
def householder_reflection(A):
    """Householder Triangularization"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    for cnt in range(r - 1):
        x = R[cnt:, cnt]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_cnt = np.identity(r)
        Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_cnt, R)  # R=H(n-1)*...*H(2)*H(1)*A
        Q = np.dot(Q, Q_cnt)  # Q=H(n-1)*...*H(2)*H(1)  H is the self inverse matrix
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = householder_reflection(A)
print(Q)
print(R)
print(np.dot(Q, R))

Concept explanation

A linear subspace of V is a subset U⊆V that is closed under vector addition and scalar multiplication. That is, for all u1,u2∈U and α∈R, it holds that u1+u2∈U and αu1∈U.

In [ ]:
# creating a 1-D list (Horizontal)
list1 = [5, 6, 9]
 
# creating a 1-D list (Horizontal)
list2 = [1, 2, 3]

# creating first vector
vector1 = np.array(list1)
 
# printing vector1
print("First Vector   : " + str(vector1))
 
# creating second vector
vector2 = np.array(list2)
 
# printing vector2
print("Second Vector  : " + str(vector2))

addition = vector1 + vector2
 
# printing addition vector
print("Vector Addition: " + str(addition))

scalarmult = 2 * vector1

# printing scalar multiplication vector
print("Vector Addition: " + str(scalarmult))

# as long as vector1 and vector2 belongs to U, 
# addition vector and scalarmult vector both belongs to U

First Vector   : [5 6 9]
Second Vector  : [1 2 3]
Vector Addition: [ 6  8 12]
Vector Addition: [10 12 18]
